# Copyright 2025 ReliQuary Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

imports:
- path: reliquary.jinja

resources:
- name: reliquary-deployment
  type: reliquary.jinja
  properties:
    zone: {{ properties["zone"] }}
    machineType: {{ properties["machineType"] }}
    adminEmail: {{ properties["adminEmail"] }}
    sshPublicKey: {{ properties["sshPublicKey"] }}
    dnsName: {{ properties["dnsName"] }}