# fly.toml app configuration file generated for reliquary on 2025-08-29T15:30:00+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reliquary"
primary_region = "iad"

[build]
  image = "reliquary/platform:v5.0.0"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024