name: Publish Go SDK

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/go

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Verify module
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Tag and push to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ github.event.release.tag_name }}"
          git push origin "v${{ github.event.release.tag_name }}"
